name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."

inputs:
  node-version:
    required: true
    description: NodeJS version to use
    default: 20.x
  working-dir:
    description: The working directory of the application
    default: .
    required: false
runs:
  using: composite
  steps: 
    - name: Setup Node ${{  inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{  inputs.node-version }}
        
    - name: Download cached dependencies
      id: cache
      uses: actions/cache@v3
      with:
        key: node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
        path: ${{ inputs.working-dir }}/node-modules
    - name: Install Dependencies
      if: steps.cached.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
      inputs.working-directory: ${{ inputs.working-dir }}
      
