name: 04 - Using Actions
on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run: 
            working-directory: 04- Using-actions/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: SetUp Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Npm install
              run: npm install
            - name: Install Dependencies
              run: npm ci
            - name: npm task to build
              run: npm run build
            - name: npm task to run unit tests
              run: npm run test
            - name: npm start task
              run: npm run start

              
              
