name: 12 - Working with Outputs
on:
    workflow_dispatch: 
        inputs:
            build-status:
                type: choice
                options: 
                    - failure
                    - success
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
            output1_value: ${{ steps.build.outputs.output1}}
            output2_value: ${{ steps.build.outputs.output2}}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo "$GITHUB_OUTPUT"
            
            - name: Build
              id: build
              run: |
                echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
                echo "output1= "value 1" >> "$GITHUB_OUTPUT"
                echo "output2= "value2" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
                echo "mistake=true" > "$GITHUB_OUTPUT"
            - name: Step with mistake
              run: |
                echo "output2= "value2" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"

    deploy: 
        runs-on: ubuntu-latest
        needs: build
        if: ${{needs.build.outputs.build-status == 'success' }}
        steps: 
            - name: Deploy
              run: |
                echo "deploying"
                echo "${{ needs.build.outputs.output1_value}}"
                echo "${{ needs.build.outputs.output2_value}}"